export const tooltips = [
    { type: "edit", title: "EDIT_TOOL_TITLE", description: "EDIT_TOOL_DESCRIPTION", shortcut: "EDIT_TOOL_SHORTCUT" },
    { type: "pan", title: "PAN_TOOL_TITLE", description: "PAN_TOOL_DESCRIPTION", shortcut: "PAN_TOOL_SHORTCUT" },
    { type: "point", title: "POINT_TOOL_TITLE", description: "POINT_TOOL_DESCRIPTION", shortcut: "POINT_TOOL_SHORTCUT" },
    {
        type: "line",
        title: "Line Tool",
        description: "Create a polyline which can be expanded to contain many sections.Hold Shift to get a 45 degree angle lock while drawing.",
        shortcut: "Ctrl + 3",
    },
    {
        type: "polygon",
        title: "Area Tool",
        description: "Create a polygon/area which contains most values. You can draw diagonally and get a perfect rectangle by right clicking the second point",
        shortcut: "Ctrl + 4",
    },
    { type: "ellipse", title: "ELlIPSE_TOOL_TITLE", description: "ElLIPSE_TOOL_DESCRIPTION", shortcut: "ELLIPSE_TOOL_SHORTCUT" },
    { type: "freehand", title: "FREEHAND_TOOL_TITLE", description: "FREEHAND_TOOL_DESCRIPTION", shortcut: "FREEHAND_TOOL_SHORTCUT" },
    { type: "reduction", title: "REDUCTION_TOOL_TITLE", description: "REDUCTION_TOOL_DESCRIPTION", shortcut: "REDUCTION_TOOL_SHORTCUT" },
    { type: "text", title: "TEXT_TOOL_TITLE", description: "TEXT_TOOL_DESCRIPTION", shortcut: "TEXT_TOOL_SHORTCUT" },
    { type: "stamp", title: "STAMP_TOOL_TITLE", description: "STAMP_TOOL_DESCRIPTION", shortcut: "STAMP_TOOL_SHORTCUT" },
    { type: "arrow", title: "ARROW_TOOL_TITLE", description: "ARROW_TOOL_DESCRIPTION", shortcut: "ARROW_TOOL_SHORTCUT" },
    { type: "zoom", title: "ZOOM_TOOL_TITLE", description: "ZOOM_TOOL_DESCRIPTION", shortcut: "ZOOM_TOOL_SHORTCUT" },
    { type: "fit", title: "FIT_TO_SCREEN_TOOL_TITLE", description: "FIT_TO_SCREEN_TOOL_DESCRIPTION", shortcut: "FIT_TO_SCREEN_TOOL_SHORTCUT" },
    { type: "download", title: "DOWNLOAD_FILE_TITLE", description: "DOWNLOAD_FILE_DESCRIPTION", shortcut: "DOWNLOAD_FILE_SHORTCUT" },
    { type: "export", title: "EXPORT_FILE_TITLE", description: "EXPORT_FILE_DESCRIPTION", shortcut: "EXPORT_FILE_SHORTCUT" },
    { type: "filter", title: "FILETER_TOOL_TITLE", description: "FILTER_TOOL_DESCRIPTION", shortcut: "FILTER_TOOL_SHORTCUT" },
    { type: "snapOn", title: "SNAPON_TOOL_TITLE", description: "SNAPON_TOOL_DESCRIPTION", shortcut: "SNAPON_TOOL_SHORTCUT" },
    { type: "template", title: "TEMPLATE_TOOL_TITLE", description: "TEMPLATE_TOOL_DESCRIPTION", shortcut: "TEMPLATE_TOOL_SHORTCUT" },
];
